/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adivinaanimales;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alejandro
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    
    Tree adivinador = new Tree();
    Tree grafico = new Tree();
    Nodo aux;
    boolean pausa = true;
    boolean modificador = false;         

    public View() throws IOException {
        
        adivinador.inicio();
        adivinador.leerConocimientos(adivinador.getRaiz(), true);
        adivinador.resetear();
        adivinador.actualizarConocimientos(adivinador.getRaiz(), true);
        initComponents();
        aux = adivinador.getRaiz();
        jlabel6.setText(aux.getInfo());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        si = new javax.swing.JToggleButton();
        no = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        iniciar = new javax.swing.JButton();
        resetear = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        si.setText("Si");
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });

        no.setText("No");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        iniciar.setText("Iniciar");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        resetear.setText("Resetear conocimientos");
        resetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetearActionPerformed(evt);
            }
        });

        mostrar.setText("Mostrar conocimientos");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel3.setText("ADIVINADOR DE ANIMALES");

        jlabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mostrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(si)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(no)))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel3)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2))
                            .addComponent(resetear)
                            .addComponent(iniciar))
                        .addContainerGap(64, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(jlabel6)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlabel6)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si)
                    .addComponent(no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(iniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostrar)
                    .addComponent(salir))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        
        adivinador.setRespuesta(false);
        if(!(aux.getInfo().equals("Tiene que ser un animal") || aux.getInfo().equals("¡Adiviné!") || aux.getInfo().equals("Inicio: intentar de nuevo") || jlabel6.getText().equals("Inicio: intentar de nuevo"))){
            
            if(aux.isPregunta()==false){
            
                                
                String aux1 = "";
                String aux2 = "";
                boolean aux3 = true;
                
                NuevoNodo insertar = new NuevoNodo(this, true);   
                insertar.setEncabezado(aux.getInfo());
                insertar.setVisible(true);    
                
                jlabel6.setText(aux.getHijoD().getInfo());
                pausa = false;
                
                while(pausa == false){
                    
                    try{
                        Thread.sleep(500);
                    }catch(InterruptedException ex){
                        Thread.currentThread().interrupt();
                    }
                    
                    pausa = insertar.isPausa();
                    aux1 = insertar.getRespuesta();
                    aux2 = insertar.getPregunta();
                    aux3 = insertar.isModificador();
                    
                }
                
                adivinador.insertar(adivinador.find(adivinador.getRaiz(), aux.getInfo()), aux2, aux1, aux3);
                try {
                    adivinador.resetear();
                    adivinador.actualizarConocimientos(adivinador.getRaiz(), true);
                } catch (IOException ex) {
                    Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }else{
            
                aux = adivinador.mover(adivinador.find(adivinador.getRaiz(), aux.getInfo()));
            
                
                if(aux.getInfo().equals("Tiene que ser un animal")){
                    jlabel6.setText(aux.getInfo());
                }else if(aux.isPregunta()==false){
                    jlabel6.setText("¿Es un " + aux.getInfo() + "?");
                }else{
                    jlabel6.setText("¿" + aux.getInfo() + "?");
                }
            
            }
        }
    }//GEN-LAST:event_noActionPerformed

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
        
        adivinador.setRespuesta(true);
        if(!(aux.getInfo().equals("Tiene que ser un animal") || aux.getInfo().equals("¡Adiviné!") || aux.getInfo().equals("Inicio: intentar de nuevo") || jlabel6.getText().equals("Inicio: intentar de nuevo"))){
            
            if(aux.isPregunta()==false){
                
                aux=adivinador.mover(adivinador.find(adivinador.getRaiz(), aux.getInfo()));
                jlabel6.setText(aux.getInfo());
            
            }else{
            
                aux=adivinador.mover(adivinador.find(adivinador.getRaiz(), aux.getInfo()));
            
                if(aux.isPregunta() == false){
                    jlabel6.setText("¿Es un " + aux.getInfo() + "?");
                }else{
                    jlabel6.setText("¿" + aux.getInfo() + "?");
                }
            
            }
        }
        
    }//GEN-LAST:event_siActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        grafico.setRaiz(adivinador.getRaiz().getHijoI());
        treeGUI gui = new treeGUI(grafico);
    }//GEN-LAST:event_mostrarActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        
        aux = adivinador.getRaiz();
        jlabel6.setText(aux.getInfo());
    }//GEN-LAST:event_iniciarActionPerformed

    private void resetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetearActionPerformed
        
        try {
            Tree adivinador = new Tree();
            adivinador.inicio();
            adivinador.resetear();
            adivinador.actualizarConocimientos(adivinador.getRaiz(), true);
        } catch (IOException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resetearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new View().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JButton mostrar;
    private javax.swing.JToggleButton no;
    private javax.swing.JButton resetear;
    private javax.swing.JButton salir;
    private javax.swing.JToggleButton si;
    // End of variables declaration//GEN-END:variables
}
